## argsort

In [1]:
import numpy as np

x = np.random.random_sample((10,5))
x

array([[0.13584834, 0.88809483, 0.54389937, 0.20684413, 0.65892555],
       [0.4362939 , 0.36512436, 0.6636208 , 0.56927896, 0.53843228],
       [0.57204597, 0.73540762, 0.77147478, 0.49308504, 0.24366841],
       [0.31124288, 0.40777808, 0.22807183, 0.50927423, 0.03038492],
       [0.90253933, 0.83891694, 0.87466353, 0.91832123, 0.06594177],
       [0.58009851, 0.87538777, 0.45744279, 0.3382935 , 0.7447201 ],
       [0.19295029, 0.09040076, 0.70884755, 0.63950947, 0.66888737],
       [0.06301225, 0.18002833, 0.29218235, 0.45402853, 0.24505396],
       [0.45213553, 0.72860828, 0.13543054, 0.01756567, 0.97500704],
       [0.78917459, 0.1340449 , 0.74530157, 0.06352323, 0.78700756]])

In [2]:
topk = 2
x.argsort(axis=1)

array([[0, 3, 2, 4, 1],
       [1, 0, 4, 3, 2],
       [4, 3, 0, 1, 2],
       [4, 2, 0, 1, 3],
       [4, 1, 2, 0, 3],
       [3, 2, 0, 4, 1],
       [1, 0, 3, 4, 2],
       [0, 1, 4, 2, 3],
       [3, 2, 0, 1, 4],
       [3, 1, 2, 4, 0]])

In [3]:
x.argsort(axis=1)[:,:topk]

array([[0, 3],
       [1, 0],
       [4, 3],
       [4, 2],
       [4, 1],
       [3, 2],
       [1, 0],
       [0, 1],
       [3, 2],
       [3, 1]])

In [4]:
cols = x.argsort(axis=1)[:,:topk].flatten()
cols

array([0, 3, 1, 0, 4, 3, 4, 2, 4, 1, 3, 2, 1, 0, 0, 1, 3, 2, 3, 1])

In [5]:
rows = np.repeat(np.arange(10), repeats=topk)
rows

array([0, 0, 1, 1, 2, 2, 3, 3, 4, 4, 5, 5, 6, 6, 7, 7, 8, 8, 9, 9])

In [6]:
x[rows,cols]

array([0.13584834, 0.20684413, 0.36512436, 0.4362939 , 0.24366841,
       0.49308504, 0.03038492, 0.22807183, 0.06594177, 0.83891694,
       0.3382935 , 0.45744279, 0.09040076, 0.19295029, 0.06301225,
       0.18002833, 0.01756567, 0.13543054, 0.06352323, 0.1340449 ])

In [7]:
x[rows,cols].reshape(-1,topk)

array([[0.13584834, 0.20684413],
       [0.36512436, 0.4362939 ],
       [0.24366841, 0.49308504],
       [0.03038492, 0.22807183],
       [0.06594177, 0.83891694],
       [0.3382935 , 0.45744279],
       [0.09040076, 0.19295029],
       [0.06301225, 0.18002833],
       [0.01756567, 0.13543054],
       [0.06352323, 0.1340449 ]])

## distance computation

In [8]:
from sklearn.metrics import pairwise_distances

dist = pairwise_distances(x[:2,:], x, metric='euclidean')
dist.shape

(2, 10)

In [9]:
dist

array([[0.00000000e+00, 7.23862205e-01, 7.20933186e-01, 9.20728919e-01,
        1.24798553e+00, 4.79201481e-01, 9.24166053e-01, 8.95775946e-01,
        6.54258497e-01, 1.03582586e+00],
       [7.23862205e-01, 2.10734243e-08, 5.09766662e-01, 6.84742787e-01,
        9.11855822e-01, 6.47662587e-01, 3.98353465e-01, 6.41030220e-01,
        9.52019716e-01, 7.08641498e-01]])

In [10]:
indices = dist.argsort(axis=1)[:,:3]
indices.shape

(2, 3)

In [11]:
indices

array([[0, 5, 8],
       [1, 6, 2]])

In [12]:
dist

array([[0.00000000e+00, 7.23862205e-01, 7.20933186e-01, 9.20728919e-01,
        1.24798553e+00, 4.79201481e-01, 9.24166053e-01, 8.95775946e-01,
        6.54258497e-01, 1.03582586e+00],
       [7.23862205e-01, 2.10734243e-08, 5.09766662e-01, 6.84742787e-01,
        9.11855822e-01, 6.47662587e-01, 3.98353465e-01, 6.41030220e-01,
        9.52019716e-01, 7.08641498e-01]])

In [13]:
cols = dist.argsort(axis=1)[:,:topk].flatten()
rows = np.repeat(np.arange(dist.shape[0]), repeats=topk)
dist[rows, cols].reshape(-1,topk)

array([[0.00000000e+00, 4.79201481e-01],
       [2.10734243e-08, 3.98353465e-01]])

## matrix inner product

In [14]:
a = np.random.randint(0, 3, size=(1, 3)) # similar sim
b = np.random.randint(0, 3, size=(3, 5)) # candidate history

print(a)
print(b)

[[2 0 1]]
[[2 0 0 2 0]
 [2 1 1 1 0]
 [1 0 1 2 2]]


In [15]:
c = np.dot(a, b)
print(c)
print(c.shape)

[[5 0 1 6 2]]
(1, 5)


## sparse matrix nonzero element indices

In [16]:
from scipy.sparse import csr_matrix

s = csr_matrix(np.asarray([
    [0, 0, 1, 0, 0, 2],
    [0, 0, 0, 0, 3, 0],
    [0, 4, 0, 0, 0, 0]
]))
rows, cols = s.nonzero()
print(rows)
print(cols)

[0 0 1 2]
[2 5 4 1]


In [17]:
s[0].nonzero()

(array([0, 0], dtype=int32), array([2, 5], dtype=int32))